clouds:
  dev:
    environments:
      cspr:
        regions:
          westus3: 51ee07f81c6afeabf70c18f07f8084227f664ea271081c09ad6909fe2609279e
      dev:
        regions:
          westus3: aa351b7bb2cacf1fec8d73425d7eafc4a451014535ebf26f4a7252e0911dfd5e
      ntly:
        regions:
          uksouth: 80b3e24e3782aa07c419dfebd25f836fe0e4562c9f5b11ac43df09c6e49acf32
      perf:
        regions:
          westus3: c6c4a15353116d4bf54ca695f42e8e769d292cc785b6857b2d65ea0e9a5fc53f
      pers:
        regions:
          westus3: f457099ed969e100898d44f167d93bb859b9a4bf2677c8564b6904a9925e934c
      swft:
        regions:
          uksouth: a2f93dec8eca90d989928cdadae852cffa96390d37fc92790ebe8a495bc9d60b
